# Generated by Django 4.0.3 on 2022-05-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='username',
        ),
    ]
