# Generated by Django 4.0.3 on 2022-05-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_predresults_ml_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='predresults',
            name='ml_param',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='predresults',
            name='ml_algorithm',
            field=models.CharField(default='default', max_length=30),
        ),
    ]
