# Generated by Django 4.0.3 on 2022-06-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preduser',
            old_name='username',
            new_name='nickname',
        ),
    ]
